Game merge
summer-school-2019/money-bot pull request #43
Opened 2019-08-21 14:16 UTC by BikTracker

Added game module

2019-08-21 21:17 UTC, lllumineux submitted a review, later dismissed

2019-08-22 00:51 UTC, Birdi7 requested changes

2019-08-22 00:51 UTC, Birdi7 commented on money_bot/handlers/game_handlers.py
> +a = 0
As you're getting the money of user from the db, the `a` should be removed

2019-08-22 00:51 UTC, Birdi7 commented on money_bot/handlers/game_handlers.py
> +    global a
remove

2019-08-22 00:51 UTC, Birdi7 commented on money_bot/handlers/game_handlers.py
> +    global b, a
I can't see where you save the `b` i.e. current user's bet in the database. You should save it in mongo, and remove the globals

2019-08-22 08:37 UTC, Birdi7 approved these changes

2019-08-22 08:45 UTC, merged